# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nMO18o1M5pU11VDSd_6Mek6W7HQoYspo
"""

cities = ['Москва', 'Муром', 'Навашино', 'Сергач', 'Пильна', 'Шумерля', 'Канаш', 'Урмары', 'Зелёный Дол', 'Казань Пасс']
  
print(cities[-1: -4: -1])

def delеnie():
  a = int(input("введите первое число:"))
  b = int(input("введите второе число:"))
  if b == 0:
    print("вы ввели не правельное число")
  else:
    return(a / b)



delenie()

def name(a:str):
  return("А" in  or "а" in a)



name(Алёна)

def suit_function(filter_by: str):
  return 'а' in filter_by or "А" in filter_by
 
def filter_by(suit_function, this_list: list):
    new_list = []
    for element in this_list:
        if suit_function(element):
            new_list.append(element)
    return new_list


print(filter_by(suit_function, ["фффа", "hdsbvb",]))

import telebot
import requests
import json


bot = telebot.TeleBot("5530565013:AAEsgl3orYJqTgZmlabpVRnNYZgJ2LFE6_0")


@bot.message_handler(commands=['start'])
def send_message(m):
  markup = telebot.types.ReplyKeyboardMarkup()\
    .add(telebot.types.KeyboardButton('/joke'))


  bot.send_message(
      m.chat.id,
      'нажмите на кнопку чтобы я отправил вам шутку',
      reply_markup=markup
  )



@bot.message_handler(commands=['joke'])
def send_joke(m):
    def fetch_joke():
        url = 'https://api.chucknorris.io/jokes/random'
        response = requests.request('get', url)
        raw_data = response.text
        data = json.loads(raw_data)
        return data['value']

    bot.send_message(m.chat.id, fetch_joke())


bot.infinity_polling()

import telebot
import requests
import json


bot = telebot.TeleBot("5530565013:AAEsgl3orYJqTgZmlabpVRnNYZgJ2LFE6_0")


@bot.message_handler(commands=['start'])
def send_message(m):
  markup = telebot.types.InlineKeyboardMarkup()\
    .add(telebot.types.InlineKeyboardButton('получить шутку',  callback_data='joke'))


  bot.send_message(
      m.chat.id,
      'нажмите на кнопку чтобы я отправил вам шутку',
      reply_markup=markup
  )



@bot.message_handler(func)
def send_joke(m):
    def fetch_joke():
        url = 'https://api.chucknorris.io/jokes/random'
        response = requests.request('get', url)
        raw_data = response.text
        data = json.loads(raw_data)
        return data['value']

    bot.send_message(m.chat.id, fetch_joke())


bot.infinity_polling()

import telebot
import requests
import json
import schedule

bot = telebot.TeleBot("5530565013:AAEsgl3orYJqTgZmlabpVRnNYZgJ2LFE6_0")

wait_for_time













































@bot.message_handler(commands=['start'])
def send_message(m):
  markup = telebot.types.ReplyKeyboardMarkup()\
    .add(telebot.types.KeyboardButton('/joke'))


  bot.send_message(
      m.chat.id,
      'нажмите на кнопку чтобы я отправил вам шутку',
      reply_markup=markup
  )



@bot.message_handler(commands=['joke'])
def send_joke(m):
    def fetch_joke():
        url = 'https://api.chucknorris.io/jokes/random'
        response = requests.request('get', url)
        raw_data = response.text
        data = json.loads(raw_data)
        return data['value']

    bot.send_message(m.chat.id, fetch_joke())


bot.infinity_polling()

word = input()
while word != "стоп":
  if word == "привет":
    print("привет")
  elif word == "пока":
    print("до свидания")
  else:
    print("я такого не умею")
  word = input()

from random import choice
word = input()
a = ["привет", "здравствуйте", "Hi", "прив"]
b = ["пока", "до свидания", "до новых встреч", "до завтра", "пок"]
while word != "стоп":
  if word in a:
    print(choice(a))
  elif word in b:
    print(choice(b))
  else:
    print("я такого не умею")
  word = input()

from random import choice

cart = (6, 7, 8, 9, 10)

print(choice(cart))

num = input("введите числа:")
num2 = num.split(" ")
num3 = set(num2)
print(num3)

x = int(input("введите количество углов (ограниченых 4):"))
r = []
if x == 1:
  a = input("введите координаты угла:")
  b = r.append(tuple(a.split(" ")))
elif x == 2:
  a = input("введите координаты угла:")
  b = r.append(tuple(a.split(" ")))
  c = input("введите координаты угла:")
  d = r.append(tuple(c.split(" ")))
elif x == 3:
  a = input("введите координаты угла:")
  b = r.append(tuple(a.split(" ")))
  c = input("введите координаты угла:")
  d = r.append(tuple(c.split(" ")))
  e = input("введите координаты угла:")
  f = r.append(tuple(e.split(" ")))
elif x == 4:
  a = input("введите координаты угла:")
  b = r.append(tuple(a.split(" ")))
  c = input("введите координаты угла:")
  d = r.append(tuple(c.split(" ")))
  e = input("введите координаты угла:")
  f = r.append(tuple(e.split(" ")))
  g = input("введите координаты угла:")
  q = r.append(tuple(g.split(" ")))
print(r)

x = int(input("введите число:"))
arhiv = [[], [], [], [], [], [], [], [], []]
while x == 0:
  if 100 <= x <= 199:
    a = (); arhiv.append(b)
    b = a + tuple(x)
  print(arhiv)

words = {
    "notepad": "блокнот",
    "copybook": "тетрадь"   
         }
x = input("enter the word: ")
print(word[x])

def count(from_number:int, to_number:int, step:float):
  while from_number < to_number



greet("тимур", "eng")

x = input("")
a = input("")
z = input("")
b = input("")
baza_danyih = []
while True:
  if

def bank(n:float, years:float, percent:float):
  x = n + (((n / 100) * percent) * years)
  print(x)
a
b
c
bank(, ,)



verbs = [
     "e-2008 ZGS",
     "r-2108 ZVTed",
     "e-2821 ZVB",
     "hdgfved",
]
for verbs in verbs:
  
  if verbs[-2:] == "ed":
    print(verbs + " глагол правельный")
  else:
    print(verbs + " глагол не правельный")

x = input("введите прилагательное:")
word2 = x.split("")
word = word2[-2,-1,-1]
print(word)